### PR TITLE
Fix capitalization inconsistency

### PR DESCRIPTION
**Pull request by machawk1**
At https://www.youtube.com/watch?v=1vmwTrN1Pl4&t=5m48s I noticed that the descriptions of the commands are inconsistently capitalized. This fixes the ones I could find in the repo. "Help" seems to be baked in, so will need to be fixed differently.

### CODE REVIEW

**Comment by osterbit** [comment]
first external PR 👍 🥇

**Comment by machawk1** [comment]
Once I can get it running per #217, hopefully I can submit a more code-related PR.

**Comment by b5** [comment]
Ugh I hate to be a pain, especially given the hell we're putting you through trying to get qri to build on your machine, but we use commit messages to build our CHANGELOG.md, and to make that work, we need commit messages to generate conventional changelog. Here's a vid outlining the exact steps to re-write commit messages in a mergable form:

https://asciinema.org/a/160748

this will require running `git push -f origin patch-1` once you're finished to overwrite the remote branch.

**Comment by machawk1** [comment]
@b5 Thanks for the walk-through. I have squashed and updated the PR in 5500351892941116b745e3ac8760ca8bf0d111d8.

**Pull request merged**
